import { PatientStatus } from "@prisma/client";
export interface PatientInput {
    name: string;
    age: number;
    dob: Date;
    issue: string;
    since: string;
    status?: PatientStatus;
    fullName?: string;
    gender: string;
    phone: string;
    address: string;
    bloodGroup: string;
    allergies?: string;
    weight: number;
    height: number;
}
export declare function createPatient(data: PatientInput): Promise<{
    fullName: string;
    createdAt: Date;
    id: number;
    name: string;
    age: number;
    issue: string;
    since: string;
    status: import("@prisma/client").$Enums.WorkflowStatus;
    pid: string;
    gender: string;
    dob: Date;
    phone: string;
    address: string;
    bloodGroup: string;
    allergies: string | null;
    weight: number;
    height: number;
    prescription: string | null;
    isSurgeryRequired: boolean;
    isAdmissionRecommended: boolean;
    assignedDoctorId: number | null;
}>;
export declare function listPatients(): Promise<{
    fullName: string;
    createdAt: Date;
    id: number;
    name: string;
    age: number;
    issue: string;
    since: string;
    status: import("@prisma/client").$Enums.WorkflowStatus;
    pid: string;
    gender: string;
    dob: Date;
    phone: string;
    address: string;
    bloodGroup: string;
    allergies: string | null;
    weight: number;
    height: number;
    prescription: string | null;
    isSurgeryRequired: boolean;
    isAdmissionRecommended: boolean;
    assignedDoctorId: number | null;
}[]>;
export declare function togglePatientStatus(id: number): Promise<{
    fullName: string;
    createdAt: Date;
    id: number;
    name: string;
    age: number;
    issue: string;
    since: string;
    status: import("@prisma/client").$Enums.WorkflowStatus;
    pid: string;
    gender: string;
    dob: Date;
    phone: string;
    address: string;
    bloodGroup: string;
    allergies: string | null;
    weight: number;
    height: number;
    prescription: string | null;
    isSurgeryRequired: boolean;
    isAdmissionRecommended: boolean;
    assignedDoctorId: number | null;
}>;
export declare function deletePatient(id: number): Promise<{
    fullName: string;
    createdAt: Date;
    id: number;
    name: string;
    age: number;
    issue: string;
    since: string;
    status: import("@prisma/client").$Enums.WorkflowStatus;
    pid: string;
    gender: string;
    dob: Date;
    phone: string;
    address: string;
    bloodGroup: string;
    allergies: string | null;
    weight: number;
    height: number;
    prescription: string | null;
    isSurgeryRequired: boolean;
    isAdmissionRecommended: boolean;
    assignedDoctorId: number | null;
}>;
//# sourceMappingURL=patientService.d.ts.map